#--- layout_utils.py ---
"""
layout_utils.py --- Layout creation functions for Build City Scape
======================================================================
DIGM 131 - Week 6 | Author: Ghost Fazekas Stivala

Usage:
    import layout_utils as lay
    lay.create_layout()
"""

import maya.cmds as cmds
# STAGE 4 NOTE: now that this file lives inside the `cityscape` package, the
# sibling imports use relative paths. In Stages 1-3 they were absolute
# (`import geometry_utils`) and only worked because main.py patched sys.path.
from . import geometry_utils as geo
from . import material_utils as mat
import random
import math

def build_city_block(center_x, center_z, building_count=4):
    """
    Generates a city block with a specified number of buildings arranged in a circular pattern.

    This function positions a series of buildings around a central point on the x and z axes,
    using an even angular distribution. The height of each building increases in proportion
    to its index in the arrangement. The width and depth of all buildings are fixed.

    Parameters:
        center_x (float): The x-coordinate of the center of the city block.
        center_z (float): The z-coordinate of the center of the city block.
        building_count (int): The number of buildings to create in the city block. Defaults to 4.

    Returns:
        list: A list of buildings, where each building is generated by the create_building function.
    """
    buildings = []
    for i in range(building_count):
        angle = (2 * math.pi / building_count) * i
        offset = 2.5
        bx = center_x + math.cos(angle) * offset
        bz = center_z + math.sin(angle) * offset

        height = 3.0 * (i * 2.5)
        building = geo.create_building(bx, bz, width=1.8, height=height, depth=1.8)
        buildings.append(building)
    return buildings

def build_park(center_x, center_z, tree_count=6, radius=5.0):
    """
    Builds a circular park layout by placing trees at regular intervals along the perimeter.

    Each tree consists of a trunk and a canopy which are created using the create_tree function
    for specified coordinates. The function calculates the position of each tree based on the
    provided center coordinates and the radius of the park. Trees are then evenly distributed
    around the circle based on the specified number of trees.

    Parameters:
        center_x (float): The x-coordinate of the park's central point.
        center_z (float): The z-coordinate of the park's central point.
        tree_count (int, optional): The number of trees to place around the circle. Defaults to 6.
        radius (float, optional): The radius of the circular park. Defaults to 5.0.

    Returns:
        tuple: A tuple containing two lists:
            - trunks (list): A list of tree trunk objects for the generated trees.
            - canopies (list): A list of tree canopy objects for the generated trees.
    """
    trunks = []
    canopies = []
    for i in range(tree_count):
        angle = (2 * math.pi / tree_count) * i
        tx = center_x + math.cos(angle) * radius
        tz = center_z + math.sin(angle) * radius
        trunk, canopy = geo.create_oaktree(tx, tz)
        trunks.append(trunk)
        canopies.append(canopy)
    return trunks, canopies

def line_street_with_lampposts(start_x, end_x, z, spacing=4.0):
    """
    Creates a series of lampposts along a straight line within a specified range.

    This function generates and places lampposts along a straight line, starting at the
    specified `start_x` coordinate and ending at `end_x`, with an interval defined by
    the `spacing` parameter. The `z` parameter determines the fixed coordinate for the
    line in the z-dimension. The generated lampposts are stored in a list, which is returned.

    Parameters:
        start_x (float): The starting x-coordinate for the line of lampposts.
        end_x (float): The ending x-coordinate for the line of lampposts.
        z (float): The z-coordinate where the lampposts will be placed.
        spacing (float, optional): The distance between consecutive lampposts. Defaults to 4.0.

    Returns:
        list: A list containing the generated lamppost objects, ordered sequentially from
        `start_x` to `end_x`.
    """
    posts = []
    x = start_x
    while x <= end_x:
        post = geo.create_lamppost(x, z)
        posts.append(post)
        x += spacing
    return posts

def place_in_circle(create_func, count=8, radius=10, center=(0, 0, 0), **kwargs):
    """
    Places objects in a circle using a specified creation function.

    This function arranges objects in a circular pattern around a specified
    center point. The radius of the circle, the number of objects, and an
    additional set of keyword arguments are customizable.

    Parameters:
        create_func (Callable): A callable function that creates an object.
                                It must accept two positional arguments (x, z) to
                                determine the position based on circle placement.
        count (int): The number of objects to be placed in the circle. Default is 8.
        radius (float): The radius of the circle around which the objects will
                        be placed. Default is 10.
        center (tuple): A tuple representing the 3D coordinates (x, y, z) of the
                        center of the circle. Default is (0, 0, 0).
        **kwargs: Additional keyword arguments that can be passed to the
                  `create_func`.

    Returns:
        list: A list of objects created and placed in the circular arrangement.
    """
    results = []
    for i in range(count):
        angle_degree = -(360.0 / count * i)
        angle = 2 * math.pi * i / count
        x = center[0] + radius * math.cos(angle)
        z = center[2] + radius * math.sin(angle)
        result = create_func(x, z)
        results.append(result)
        cmds.rotate(0, angle_degree - 90, 0, result)
    return results

def place_road(width, depth, start_x, end_x, z=0):
    roads = []
    x = start_x
    while x <= end_x:
        roads.append(geo.create_road(x, z, width=width, depth=depth))
        x += width  # advance by tile width
    return roads

def line_block_with_fence(center_x, center_z, block_size=5.0, post_density=0.5):
    post_count = max(2, int(block_size * post_density))
    half = block_size / 2
    parts = []

    # south + north: built along +x, just translated
    for z_off in (-half, half):
        f = geo.create_fence(length=block_size, post_count=post_count,
                             position=(center_x - half, 0, center_z + z_off))
        parts.append(f)
    # west + east: build at origin along +x, rotate 90° around y, then move
    for x_off in (-half, half):
        f = geo.create_fence(length=block_size, post_count=post_count, position=(0, 0, 0))
        cmds.xform(f, pivots=(0, 0, 0), worldSpace=True)
        cmds.rotate(0, 90, 0, f)
        cmds.move(center_x + x_off, 0, center_z - half, f)
        parts.append(f)
    return cmds.group(parts, name="block_fence_#")

def place_people(center_x, center_z, people_number, spread=4.0):
    people = []
    for _ in range(people_number):
        px = center_x + random.uniform(-spread, spread)
        pz = center_z + random.uniform(-spread, spread)
        people.append(geo.create_person(px, pz))
    return people